//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("eventcitydbModel", "accounts_events", "account", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Eventcity.Models.accounts), "events", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Eventcity.Models.events))]

#endregion

namespace Eventcity.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class eventcitydbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new eventcitydbEntities object using the connection string found in the 'eventcitydbEntities' section of the application configuration file.
        /// </summary>
        public eventcitydbEntities() : base("name=eventcitydbEntities", "eventcitydbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new eventcitydbEntities object.
        /// </summary>
        public eventcitydbEntities(string connectionString) : base(connectionString, "eventcitydbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new eventcitydbEntities object.
        /// </summary>
        public eventcitydbEntities(EntityConnection connection) : base(connection, "eventcitydbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<events> events
        {
            get
            {
                if ((_events == null))
                {
                    _events = base.CreateObjectSet<events>("events");
                }
                return _events;
            }
        }
        private ObjectSet<events> _events;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<accounts> accounts
        {
            get
            {
                if ((_accounts == null))
                {
                    _accounts = base.CreateObjectSet<accounts>("accounts");
                }
                return _accounts;
            }
        }
        private ObjectSet<accounts> _accounts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the events EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToevents(events events)
        {
            base.AddObject("events", events);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccounts(accounts accounts)
        {
            base.AddObject("accounts", accounts);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eventcitydbModel", Name="accounts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class accounts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new accounts object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        public static accounts Createaccounts(global::System.Int32 pK)
        {
            accounts accounts = new accounts();
            accounts.PK = pK;
            return accounts;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.Int32 _PK;
        partial void OnPKChanging(global::System.Int32 value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strUserName
        {
            get
            {
                return _strUserName;
            }
            set
            {
                OnstrUserNameChanging(value);
                ReportPropertyChanging("strUserName");
                _strUserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strUserName");
                OnstrUserNameChanged();
            }
        }
        private global::System.String _strUserName;
        partial void OnstrUserNameChanging(global::System.String value);
        partial void OnstrUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strPassword
        {
            get
            {
                return _strPassword;
            }
            set
            {
                OnstrPasswordChanging(value);
                ReportPropertyChanging("strPassword");
                _strPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strPassword");
                OnstrPasswordChanged();
            }
        }
        private global::System.String _strPassword;
        partial void OnstrPasswordChanging(global::System.String value);
        partial void OnstrPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strName
        {
            get
            {
                return _strName;
            }
            set
            {
                OnstrNameChanging(value);
                ReportPropertyChanging("strName");
                _strName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strName");
                OnstrNameChanged();
            }
        }
        private global::System.String _strName;
        partial void OnstrNameChanging(global::System.String value);
        partial void OnstrNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strStatus
        {
            get
            {
                return _strStatus;
            }
            set
            {
                OnstrStatusChanging(value);
                ReportPropertyChanging("strStatus");
                _strStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strStatus");
                OnstrStatusChanged();
            }
        }
        private global::System.String _strStatus;
        partial void OnstrStatusChanging(global::System.String value);
        partial void OnstrStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strHomeCity
        {
            get
            {
                return _strHomeCity;
            }
            set
            {
                OnstrHomeCityChanging(value);
                ReportPropertyChanging("strHomeCity");
                _strHomeCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strHomeCity");
                OnstrHomeCityChanged();
            }
        }
        private global::System.String _strHomeCity;
        partial void OnstrHomeCityChanging(global::System.String value);
        partial void OnstrHomeCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strHomeState
        {
            get
            {
                return _strHomeState;
            }
            set
            {
                OnstrHomeStateChanging(value);
                ReportPropertyChanging("strHomeState");
                _strHomeState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strHomeState");
                OnstrHomeStateChanged();
            }
        }
        private global::System.String _strHomeState;
        partial void OnstrHomeStateChanging(global::System.String value);
        partial void OnstrHomeStateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eventcitydbModel", "accounts_events", "events")]
        public EntityCollection<events> events
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<events>("eventcitydbModel.accounts_events", "events");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<events>("eventcitydbModel.accounts_events", "events", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eventcitydbModel", Name="events")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class events : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new events object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        /// <param name="bIsDeleted">Initial value of the bIsDeleted property.</param>
        /// <param name="strEventImg">Initial value of the strEventImg property.</param>
        public static events Createevents(global::System.Int32 pK, global::System.Boolean bIsDeleted, global::System.String strEventImg)
        {
            events events = new events();
            events.PK = pK;
            events.bIsDeleted = bIsDeleted;
            events.strEventImg = strEventImg;
            return events;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.Int32 _PK;
        partial void OnPKChanging(global::System.Int32 value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strEventName
        {
            get
            {
                return _strEventName;
            }
            set
            {
                OnstrEventNameChanging(value);
                ReportPropertyChanging("strEventName");
                _strEventName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strEventName");
                OnstrEventNameChanged();
            }
        }
        private global::System.String _strEventName;
        partial void OnstrEventNameChanging(global::System.String value);
        partial void OnstrEventNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strEventDescription
        {
            get
            {
                return _strEventDescription;
            }
            set
            {
                OnstrEventDescriptionChanging(value);
                ReportPropertyChanging("strEventDescription");
                _strEventDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strEventDescription");
                OnstrEventDescriptionChanged();
            }
        }
        private global::System.String _strEventDescription;
        partial void OnstrEventDescriptionChanging(global::System.String value);
        partial void OnstrEventDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dEventDate
        {
            get
            {
                return _dEventDate;
            }
            set
            {
                OndEventDateChanging(value);
                ReportPropertyChanging("dEventDate");
                _dEventDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dEventDate");
                OndEventDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _dEventDate;
        partial void OndEventDateChanging(Nullable<global::System.DateTime> value);
        partial void OndEventDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strHost
        {
            get
            {
                return _strHost;
            }
            set
            {
                OnstrHostChanging(value);
                ReportPropertyChanging("strHost");
                _strHost = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strHost");
                OnstrHostChanged();
            }
        }
        private global::System.String _strHost;
        partial void OnstrHostChanging(global::System.String value);
        partial void OnstrHostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean bIsDeleted
        {
            get
            {
                return _bIsDeleted;
            }
            set
            {
                OnbIsDeletedChanging(value);
                ReportPropertyChanging("bIsDeleted");
                _bIsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bIsDeleted");
                OnbIsDeletedChanged();
            }
        }
        private global::System.Boolean _bIsDeleted;
        partial void OnbIsDeletedChanging(global::System.Boolean value);
        partial void OnbIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strEventImg
        {
            get
            {
                return _strEventImg;
            }
            set
            {
                OnstrEventImgChanging(value);
                ReportPropertyChanging("strEventImg");
                _strEventImg = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strEventImg");
                OnstrEventImgChanged();
            }
        }
        private global::System.String _strEventImg;
        partial void OnstrEventImgChanging(global::System.String value);
        partial void OnstrEventImgChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("eventcitydbModel", "accounts_events", "account")]
        public EntityCollection<accounts> accounts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<accounts>("eventcitydbModel.accounts_events", "account");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<accounts>("eventcitydbModel.accounts_events", "account", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
