//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Eventcity.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class eventcitydbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new eventcitydbEntities object using the connection string found in the 'eventcitydbEntities' section of the application configuration file.
        /// </summary>
        public eventcitydbEntities() : base("name=eventcitydbEntities", "eventcitydbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new eventcitydbEntities object.
        /// </summary>
        public eventcitydbEntities(string connectionString) : base(connectionString, "eventcitydbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new eventcitydbEntities object.
        /// </summary>
        public eventcitydbEntities(EntityConnection connection) : base(connection, "eventcitydbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<@event> events
        {
            get
            {
                if ((_events == null))
                {
                    _events = base.CreateObjectSet<@event>("events");
                }
                return _events;
            }
        }
        private ObjectSet<@event> _events;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the events EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToevents(@event @event)
        {
            base.AddObject("events", @event);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="eventcitydbModel", Name="event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class @event : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new event object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        /// <param name="bIsDeleted">Initial value of the bIsDeleted property.</param>
        public static @event Createevent(global::System.Int32 pK, global::System.Boolean bIsDeleted)
        {
            @event @event = new @event();
            @event.PK = pK;
            @event.bIsDeleted = bIsDeleted;
            return @event;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.Int32 _PK;
        partial void OnPKChanging(global::System.Int32 value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strEventName
        {
            get
            {
                return _strEventName;
            }
            set
            {
                OnstrEventNameChanging(value);
                ReportPropertyChanging("strEventName");
                _strEventName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strEventName");
                OnstrEventNameChanged();
            }
        }
        private global::System.String _strEventName;
        partial void OnstrEventNameChanging(global::System.String value);
        partial void OnstrEventNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strEventDescription
        {
            get
            {
                return _strEventDescription;
            }
            set
            {
                OnstrEventDescriptionChanging(value);
                ReportPropertyChanging("strEventDescription");
                _strEventDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strEventDescription");
                OnstrEventDescriptionChanged();
            }
        }
        private global::System.String _strEventDescription;
        partial void OnstrEventDescriptionChanging(global::System.String value);
        partial void OnstrEventDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dEventDate
        {
            get
            {
                return _dEventDate;
            }
            set
            {
                OndEventDateChanging(value);
                ReportPropertyChanging("dEventDate");
                _dEventDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dEventDate");
                OndEventDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _dEventDate;
        partial void OndEventDateChanging(Nullable<global::System.DateTime> value);
        partial void OndEventDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> tEventTime
        {
            get
            {
                return _tEventTime;
            }
            set
            {
                OntEventTimeChanging(value);
                ReportPropertyChanging("tEventTime");
                _tEventTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tEventTime");
                OntEventTimeChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _tEventTime;
        partial void OntEventTimeChanging(Nullable<global::System.TimeSpan> value);
        partial void OntEventTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strHost
        {
            get
            {
                return _strHost;
            }
            set
            {
                OnstrHostChanging(value);
                ReportPropertyChanging("strHost");
                _strHost = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strHost");
                OnstrHostChanged();
            }
        }
        private global::System.String _strHost;
        partial void OnstrHostChanging(global::System.String value);
        partial void OnstrHostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean bIsDeleted
        {
            get
            {
                return _bIsDeleted;
            }
            set
            {
                OnbIsDeletedChanging(value);
                ReportPropertyChanging("bIsDeleted");
                _bIsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bIsDeleted");
                OnbIsDeletedChanged();
            }
        }
        private global::System.Boolean _bIsDeleted;
        partial void OnbIsDeletedChanging(global::System.Boolean value);
        partial void OnbIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strEventImg
        {
            get
            {
                return _strEventImg;
            }
            set
            {
                OnstrEventImgChanging(value);
                ReportPropertyChanging("strEventImg");
                _strEventImg = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strEventImg");
                OnstrEventImgChanged();
            }
        }
        private global::System.String _strEventImg;
        partial void OnstrEventImgChanging(global::System.String value);
        partial void OnstrEventImgChanged();

        #endregion

    
    }

    #endregion

    
}
